export default {
    EPISODE_CREATED: 'EPISODE_CREATED',
    SHOW_CREATED: 'SHOW_CREATED',
    SEASON_CREATED: 'SEASON_CREATED',
    MOVIE_CREATED: 'MOVIE_CREATED',
    LIBRARY_SCAN_STARTED: 'LIBRARY_SCAN_STARTED',
    LIBRARY_SCAN_ENDED: 'LIBRARY_SCAN_ENDED',
    TMDB_INFO_UPDATED: 'TMDB_INFO_UPDATED',
    REFRESH_IMAGES: 'REFRESH_IMAGES'
};
